export const INDICATOR_RED_COLOR = 'rgba(221,0,0,0.7)';
export const INDICATOR_RED_COLOR_BOXPLOT_FILLING = 'rgba(221,0,0,0.3)';
export const INDICATOR_BLUE_COLOR = 'rgba(0,128,255,0.7)';
export const INDICATOR_BLUE_COLOR_BOXPLOT_FILLING = 'rgba(0,128,255,0.3)';
export const INDICATOR_GREEN_COLOR = 'rgba(26,213,85,0.7)';
export const INDICATOR_GREEN_COLOR_BOXPLOT_FILLING = 'rgba(26,213,85,0.3)';
export const INDICATOR_PURPLE_COLOR = 'rgba(132,0,255,0.7)';
export const INDICATOR_PURPLE_COLOR_BOXPLOT_FILLING = 'rgba(132,0,255,0.3)';
export const SOFT_RED = 'hsl(0, 55%, 65%)';
export const SOFT_YELLOW = 'rgba(228, 190, 90, 0.7)';
export const SOFT_BLUE = 'hsl(210, 55%, 65%)';
export const SOFT_GREEN = 'hsl(135, 55%, 65%)';
export const SOFT_PURPLE = 'hsl(270, 55%, 65%)';
export const TOAST_LEFT_KEY = 'TOAST_LEFT';
export const TOAST_CENTER_KEY = 'TOAST_CENTER';
export const ALL_INDICATORS_COLORS = [
  INDICATOR_RED_COLOR,
  INDICATOR_BLUE_COLOR,
  INDICATOR_GREEN_COLOR,
  INDICATOR_PURPLE_COLOR,
];
export const ALL_INDICATORS_COLORS_BOXPLOT_FILLING = [
  INDICATOR_RED_COLOR_BOXPLOT_FILLING,
  INDICATOR_BLUE_COLOR_BOXPLOT_FILLING,
  INDICATOR_GREEN_COLOR_BOXPLOT_FILLING,
  INDICATOR_PURPLE_COLOR_BOXPLOT_FILLING,
];
export const ALL_INDICATORS_COLORS_SOFT = [
  SOFT_RED,
  SOFT_BLUE,
  SOFT_YELLOW,
  SOFT_GREEN,
  SOFT_PURPLE,
];
