import { RouteId } from "../app/models/enums/routes-id";
import { RouteEnv } from "../app/models/interfaces/env/RouteEnv";

export const routeEnvironment: RouteEnv[] = [
  {
    id: RouteId.LOGIN,
    path: "login",
    enable: true,
    title: "Login",
  },
  {
    id: RouteId.FORGOT_PASSWORD,
    path: "forgot-password",
    enable: true,
    title: "Forgot password",
  },
  {
    id: RouteId.RESET_PASSWORD,
    path: "reset-password",
    enable: true,
    title: "Reset password",
  },
  {
    id: RouteId.SET_FIRST_PASSWORD,
    path: "set-first-password",
    enable: true,
    title: "Set first password",
  },
  {
    id: RouteId.DASHBOARD,
    path: "dashboard",
    enable: true,
    isPrincipal: true,
    title: "Dashboard",
  },
  {
    id: RouteId.COST_REQUEST,
    path: "requests",
    enable: true,
    isPrincipal: true,
    title: "Requests",
    children: [
      {
        id: RouteId.QUOTATION,
        path: "quotation",
        title: "Quotation",
        detailBackLink: RouteId.COST_REQUEST,
        enable: true,
      },
      {
        id: RouteId.COST_REQUEST_COSTING,
        path: "costing",
        title: "Costing",
        detailBackLink: RouteId.COST_REQUEST,
        enable: true,
      },
    ],
  },
  {
    id: RouteId.ENGINEERING,
    path: "engineering",
    enable: true,
    isPrincipal: true,
    title: "Engineering",
    children: [
      {
        id: RouteId.ENGINEERING_QUOTATION,
        path: "quotation",
        title: "Quotation",
        detailBackLink: RouteId.ENGINEERING,
        enable: true,
      },
      {
        id: RouteId.ENGINEERING_COSTING,
        path: "costing",
        title: "Costing",
        detailBackLink: RouteId.ENGINEERING,
        enable: true,
      },
    ],
  },
  {
    id: RouteId.PROCUREMENT,
    path: "procurement",
    enable: true,
    isPrincipal: true,
    title: "Procurement",
    children: [
      {
        id: RouteId.PROCUREMENT_MATERIAL,
        path: "material",
        enable: true,
        title: "Material",
        detailBackLink: RouteId.PROCUREMENT,
        children: [
          {
            id: RouteId.MATERIALS_TO_ESTIMATE,
            path: "material-to-estimate",
            title: "To estimate",
            detailBackLink: RouteId.PROCUREMENT_MATERIAL,
            enable: true,
          },
          {
            id: RouteId.MATERIALS_ESTIMATED,
            path: "material-estimated",
            title: "Estimated",
            detailBackLink: RouteId.PROCUREMENT_MATERIAL,
            enable: true,
          },
        ],
      },
      {
        id: RouteId.PROCUREMENT_TOOLING,
        path: "tooling",
        enable: true,
        title: "Tooling",
      },
      {
        id: RouteId.PROCUREMENT_COST_REQUEST_LINE,
        path: "part-number",
        enable: true,
        title: "Part number",
        detailBackLink: RouteId.PROCUREMENT,
      },
    ],
  },
  {
    id: RouteId.APPROVAL,
    path: "approval",
    enable: true,
    isPrincipal: true,
    title: "Approval",
    children: [
      {
        id: RouteId.MANAGEMENT_PENDING_APPROVAL,
        path: "pending-approval",
        title: "Pending Approval",
        detailBackLink: RouteId.APPROVAL,
        enable: true,
      },
    ],
  },
  {
    id: RouteId.PLANNING,
    path: "planning",
    enable: true,
    isPrincipal: true,
    title: "Planning",
    children: [
      {
        id: RouteId.PLANNING_LIST,
        path: "list",
        title: "BOM",
        detailBackLink: RouteId.PLANNING,
        enable: true,
      },
    ],
  },
  {
    id: RouteId.INDICATORS,
    path: "indicators",
    enable: true,
    isPrincipal: true,
    title: "Indicators",
    children: [
      {
        id: RouteId.INDICATORS_CSR,
        path: "costing",
        enable: true,
        detailBackLink: RouteId.INDICATORS,
        title: "Costing",
        children: [
          {
            id: RouteId.COST_REQUESTS_MONTHLY_ACTIVE_LEAD_TIME,
            path: "cost-requests-monthly-active-lead-time",
            title: "CR active LT",
            detailBackLink: RouteId.INDICATORS_CSR,
            enable: false,
          },
          {
            id: RouteId.COST_REQUESTS_MONTHLY_ACTIVE,
            path: "cost-requests-monthly-active",
            title: "CR active count",
            detailBackLink: RouteId.INDICATORS_CSR,
            enable: false,
          },
        ],
      },
    ],
  },
  {
    id: RouteId.REPORT,
    path: "report",
    enable: true,
    isPrincipal: true,
    title: "Report",
  },
  {
    id: RouteId.BOM_CONFIGURATIONS,
    path: "bom-configurations",
    enable: true,
    isPrincipal: true,
    title: "BOM Configurations",
  },
  {
    id: RouteId.ADMIN,
    path: "administration",
    enable: true,
    isPrincipal: true,
    title: "Admin",
    children: [
      {
        id: RouteId.ADMIN_USERS,
        path: "users",
        title: "Users",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
      {
        id: RouteId.ADMIN_CUSTOMERS,
        path: "customers",
        title: "Customers",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
      {
        id: RouteId.ADMIN_PRODUCT_NAMES,
        path: "product-names",
        title: "Product Names",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
      {
        id: RouteId.ADMIN_MATERIAL_CATEGORIES,
        path: "material-categories",
        title: "Material Categories",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
      {
        id: RouteId.ADMIN_CURRENCIES,
        path: "currencies",
        title: "Currencies",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
      {
        id: RouteId.ADMIN_PROCESSES,
        path: "processes",
        title: "Processes",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
      {
        id: RouteId.ADMIN_SHIPMENT_METHODS,
        path: "shipment-methods",
        title: "Shipment Methods",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
      {
        id: RouteId.ADMIN_UNITS,
        path: "units",
        title: "Units",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
      {
        id: RouteId.ADMIN_SUPPLIERS_MANUFACTURERS,
        path: "suppliers-manufacturers",
        title: "Suppliers & Manufacturers",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
      {
        id: RouteId.ADMIN_GLOBAL_CONFIG,
        path: "global-config",
        title: "Global Configuration",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
      {
        id: RouteId.ADMIN_SHIPMENT_LOCATIONS,
        path: "shipment-locations",
        title: "Shipment Locations",
        detailBackLink: RouteId.ADMIN,
        enable: true,
      },
    ],
  },
];
