export enum NpiOrderFormField {
  PURCHASE_ORDER_NUMBER = "purchaseOrderNumber",
  WORK_ORDER_ID = "workOrderId",
  PART_NUMBER = "partNumber",
  QUANTITY = "quantity",
  ORDER_DATE = "orderDate",
  TARGET_DELIVERY_DATE = "targetDeliveryDate",
  CUSTOMER_NAME = "customerName",
  PRODUCT_NAME = "productName",
  MATERIAL_PURCHASE_PLAN_TIME_IN_DAYS = "materialPurchasePlanTimeInDays",
  MATERIAL_RECEIVING_PLAN_TIME_IN_DAYS = "materialReceivingPlanTimeInDays",
  PRODUCTION_PLAN_TIME_IN_DAYS = "productionPlanTimeInDays",
  TESTING_PLAN_TIME_IN_DAYS = "testingPlanTimeInDays",
  SHIPPING_PLAN_TIME_IN_DAYS = "shippingPlanTimeInDays",
  CUSTOMER_APPROVAL_PLAN_TIME_IN_DAYS = "customerApprovalPlanTimeInDays",
}
